### ISSUE TITLE
13.19

### ISSUE THREAD

**Issue by readyztw** [lucifer00123/Handbot#1]
can you please update the release if there is 13.19version? im sorry for wasting ur time

**Comment by lucifer00123** [comment]
> can you please update the release if there is 13.19version? im sorry for wasting ur time

Hey it’s no problem at all and if you want for consent update join our telegram group 
https://t.me/HandbotNeverDieChat
https://t.me/HandbotNeverDieShards

**Comment by lucifer00123** [comment]
Done I updated the zip for the latest version once I am home I’ll fix some bugs and upload another one, and if you have a discord send me ur user that would make talking easy.

**Comment by lucifer00123** [comment]
Send me ur user on discord and it’s no problem at all
