### ISSUE TITLE
Offsets for the new version

### ISSUE THREAD

**Issue by AmenHermano144** [lucifer00123/Handbot#2]
It's a shame I can't update it because I don't have the source, but here I leave the offsets so you can do it yourself, if you want help just tell me
Discord: diegote
Good project, it was fun to use while it lasted
namespace Offsets
{
	enum Functions {
		IsHero = 0x25B650, 										//13.19 
		IsMinion = 0x25B6B0,									//13.19
		IsMissile = 0x25B6E0, 									//13.19
		IsTurret = 0x25B550,									//13.19
		IsAlive = 0x244C20,										//13.19
 
		fGetAttackDelay = 0x3BE9E0,								//13.19
		fGetAttackCastDelay = 0x3BE8E0,							//13.19
		IssueClick = 0x8B1F70,									//13.19
 
		GetPing = 0x4951B0,										//13.19	//search string "game.enetLatency"
		GetBoundingRadius = 0x1FC480,							//13.19
		HudCastSpell = 0x88EC90,								//13.19
		HudCastSpellPacket = 0x6FA6E0,							//13.18
		SpoofGadget = 0xF7F0E3,									//13.5	 ////// search "FF 23"
		//BaseDrawPosition = 0x1FEED0,							//13.
		GetCollisionFlags = 0xD8EFB0,							//13.19
		GetObjectFromNetId = 0x39E360,							//13.19
		OnProcessSpellCast = 0x70BB50,							//13.19
		WorldToScreen = 0xE18A50,								//13.19
		SendPing = 0x190A80,									//13.19
		GetRespawnTime = 0x202D10,								//13.19
 
 
	};
 
	enum Data {
		GameTime = 0x21B8D2C, 									//13.19
		NetClient = 0x21A9858,									//13.19
		ViewProjMatrix = 0x220D4D0, 							//13.19
		Viewport = 0x21AC7B0, 									//13.19
		Renderer = 0x2215E60,									//13.19
		RendererWidth = 0xC,									//13.19
		RendererHeight = 0x10,									//13.19
 
		LocalPlayer = 0x21C4A28,								//13.19
		HeroManager = 0x21A9988,								//13.19
 
		HudInstance = 0x21A9878,								//13.19
		HudInstance_Input = 0x28,								//13.19
		HudInstance_UserData = 0x60,							//13.17
		HudInstance_SpellInfo = 0x68,							//13.17
		HudInstance_Camera = 0x18,								//13.19
		HudInstance_CameraZoom = 0x2B8,							//13.19
 
		BuildingManager = 0x21A5AE8,							//13.19
		MinionManager = 0x21AC7F0,								//13.19
		TurretManager = 0x21B3090,								//13.19
		ObjectManager = 0x21A9868,								//13.19
		MissileManager = 0x21C5CF0,								//13.19
		InhibManager = 0x21C5EE8,								//13.19
		UnderMouseObject = 0x21AC9E0,							//13.19
		ZoomInstance = 0x21AEE50,								//13.19
		ZoomInstance_MaxZoom = 0x28								//13.19
 
	};
 
	enum gObject {
		Team = 0x3C,											//13.19
		NetworkID = 0x10,										//13.19
		Pos = 0x220,											//13.19
		Visibility = 0x310,										//13.19
		CombatType = 0x1FB8,									//13.5		//83 B9 ? ? ? ? ? 0F 94 C0 C3 CC CC CC CC CC 51 0F B6 81 ? ? ? ? 56
		Mana = 0x0340,											//13.19
		MaxMana = 0x358,										//13.19
		ManaRegen = 0x14cc,										//13.19
		RecallState = 0xF40,									//13.19
		Health = 0x1058,										//13.19
		HealthRegen = 0x16A8,									//13.19
		MaxHealth = 0x1070,										//13.19
		
		LifeStealPercent = 0x1650,								//13.19
		
		AbilityHaste = 0x1498,									//13.19
		LethalityPercent = 0x1598,								//13.19
		
		Armor = 0x1694,											//13.19
		BonusArmor = 0x1698,									//13.19
		
		MagicRes = 0x169C,										//13.19
		BonusMagicRes = 0x16A0,									//13.19
		
		AbilityPower = 0x15E8,									//13.19
		AbilityPowerPercent = 0x15EC,							//13.19
 
		BaseAtkDamage = 0x166C,									//13.19
		BonusAtkDamage = 0x15d8,								//13.19
		
		//MagicPenetrationPercent = 0x15d8,						//13.19
		
		MoveSpeed = 0x16AC,										//13.19
		PlayerName = 0x60,										//13.19
		Name = 0x3858,											//13.19
		Lvl = 0x3FC0,											//13.19
		Crit = 0x1C78,											//13.19
		AtkRange = 0x16B4,										//13.19
		Targetable = 0xEB0,										//13.19
		Direction = 0x2190,										//13.19
		isInvulnerable = 0x4F0,									//13.19
		IsTargetableToTeam = 0xD14,								//13.5
		ActionState = 0x13C3,									//13.17
		Scale = 0x1684,											//13.19 // or 16a8
		CurrentTargetIndex = 0x3890								//13.19
	};
 
	enum Missile
	{
		MissileInfo = 0x2E8,										//13.18
		MissileInfoMissileName1 = 0x28,								//13.18
		MissileInfoMissileName2 = 0x118,							//13.18
		MissileInfoMissileName3 = 0x208,							//13.18
		MissileInfoMissileName4 = 0x2F8,							//13.18
		MissileInfoMissileName5 = 0x3E8,							//13.18
		MissileInfoMissileName6 = 0x4D8,							//13.18
		
 
		MissileData = 0x28,											//13.18
 
 
		MissileStartPos = 0x38C,									//13.17 //Vector3
		MissileEndPos = 0x398,										//13.17 //Vector3
		MissileDstIndex = 0x3C8,									//13.18 
		MissileSrcIndex = 0x370,									//13.18 //attackers netid
		MissileName = 0x60,											//13.18
		MissileCasterName = 0x308,									//13.18 // name of the obj, that is casting missile
 
	};
 
	enum Spells {
 
		//Q=0,W=1,E=2,3=R
		//SpellObject : [[<League of Legends.exe> + 0x21C4A28]+30B8 +(0x8 *SPELLINDEX)]
		//SpellSlotLevel : [[<League of Legends.exe> + 0x21C4A28]+30B8 +(0x8 *3)]+0x28
		//SpellSlotCooldown : [[<League of Legends.exe> + 0x21C4A28]+30B8 +(0x8 *3)]+0x30
		//SpellSlotCooldownSmite : [[<League of Legends.exe> + 0x21C4A28]+30B8 +(0x8 *5)]+0x68
		//SpellSlotTotalCooldown : [[<League of Legends.exe> + 0x21C4A28]+30B8 +(0x8 *3)]+0x74
		//SpellSlotDamage : [[<League of Legends.exe> + 0x21C4A28]+30B8 +(0x8 *3)]+0x90
		//SpellSlotStacks : [[<League of Legends.exe> + 0x21C4A28]+30B8 +(0x8 *3)] idk
		
		//SpellSlotSpellInput : [[[<League of Legends.exe> + 0x21C4A28]+30B8 +(0x8 *1)]+0x128]
		//SpellInputTargetNetId : [[[<League of Legends.exe> + 0x21C4A28]+30B8 +(0x8 *1)]+0x128]+0x14
		//SpellInputSourceNetId : [[[<League of Legends.exe> + 0x21C4A28]+30B8 +(0x8 *1)]+0x128]+0x10
		//SpellInputStartPos : [[[<League of Legends.exe> + 0x21C4A28]+30B8 +(0x8 *1)]+0x128]+0x18
		//SpellInputEndPos : [[[<League of Legends.exe> + 0x21C4A28]+30B8 +(0x8 *1)]+0x128]+0x24
		
		//SpellSlotSpellInfo : [[[<League of Legends.exe> + 0x21C4A28]+30B8 +(0x8 *1)]+0x130]
		//SpellInfoSpellData : [[[[<League of Legends.exe> + 0x21C4A28]+30B8 +(0x8 *1)]+0x130]+0x60]
		//SpellDataSpellName : [[[[<League of Legends.exe> + 0x21C4A28]+30B8 +(0x8 *1)]+0x130]+0x60]+0x80
		//SpellDataManaCostArray :  [[[[<League of Legends.exe> + 0x21C4A28]+30B8 +(0x8 *1)]+0x130]+0x60]+0x604
		//SpellDataCooldown :  [[[[<League of Legends.exe> + 0x21C4A28]+30B8 +(0x8 *1)]+0x130]+0x60]+0x2f4
 
			
		//		*SpellObject
		//			-SpellSlotLevel
		//			-SpellSlotCooldown
		//			-SpellSlotTotalCooldown
		//			-SpellSlotStacks
		//			-SpellSlotDamage
		//			
		//			+SpellSlotSpellInput
		//				-SpellInputTargetNetId
		//				-SpellInputStartPos
		//				-SpellInputEndPos
		// 
		//			+SpellSlotSpellInfo
		//				-SpellInfoSpellData
		//					-SpellDataSpellName
		//					-SpellDataManaCostArray
 
 
		Spellbook = 0x30B8,										//13.19
 
		HudInstanceSpellInfo = 0x68,							//13.17
		SpellBookSpellSlot = 0x6D0,								//13.17 //idk, need to recheck, i think broken
		
		SpellBookSpellCast = 0x2A20,							//13.18
		SpellCastSpellInfo = 0x8, 								//13.
		SpellCastSpellType = 0x10, 								//13.18
		SpellCastSpellId = 0x124, 								//13.
 
		SpellSlotLevel = 0x28, 									//13.19
		SpellSlotCooldown = 0x30, 								//13.19 final gametime, when spell is ready
		SpellSlotCooldownSmite = 0x68, 							//13.19
		SpellSlotStacks = 0x5C, 								//13.
		SpellSlotTotalCooldown = 0x74, 							//13.19 total cooldown time
		SpellSlotDamage = 0x90, 								//13.19 //smite, ignite
		SpellSlotSpellInfo = 0x130, 							//13.19
		SpellInfoSpellData = 0x60, 								//13.19
		
		SpellDataSpellName = 0x80, 								//13.19
		SpellDataManaCostArray = 0x604, 						//13.19 ARRAY, add + 0x4
		SpellDataCooldown = 0x2f4, 								//13.19 ARRAY, add + 0x4
 
		SpellSlotSpellInput = 0x128, 							//13.19
		SpellInputTargetNetId = 0x14, 							//13.19 // attacker's source // mostly spells like nasus w, evelyn e...
		SpellInputSourceNetId = 0x10, 							//13.19 // attacker
		SpellInputStartPos = 0x18, 								//13.19 vec3
		SpellInputEndPos = 0x24, 								//13.19 vec3
 
 
	};
 
	enum Chat {
		ChatInst = 0x21C5D90,									//13.19
		IsOpen = 0xCA0,											//13.19
		PrintChat = 0x855430									//13.19
	};
 
	enum BuffManager
	{
		Instance = 0x27C8,										//13.19
		
		ArrayStart = 0x18,										//13.19
		ArrayEnd = 0x20,										//13.19
		
		StartTime = 0x18,										//13.19
		BuffEntry = 0x10,										//13.19
		EndTime = 0x1C,											//13.19
		BuffType = 0x8,											//13.19
		BuffCount = 0x3C,										//13.19
		BuffCountAlt = 0x38,									//13.19
		BuffCountAlt2 = 0x28,									//13.19
		BuffName = 0x8,											//13.19
		BuffNamePtr = 0x10,										//13.19
		BuffHash = 0x88											//13.5 // didnt check
 
	};
 
	enum Items
	{
		//ItemList = 0x40A8; ??
 
		ItemList = 0xC,											//13.5	//increment by 1, for each item //13.5
		ItemInfo = 0x20,										//13.5
		ItemInfoId = 0x68,										//13.5
	};
 
	enum Map
	{
		MinimapObject = 0x21B8D98,								//13.19 OR: search "Dragonkill" string, go to function above at the begin, after all the stuff : ecx, dword_xxxxxx, above that is: " eax, ___security_cookie"
		MinimapObjectHud = 0x320,								//13.19
		MinimapHudPos = 0x60,									//13.19
		MinimapHudSize = 0x68									//13.19
 
	};
 
	enum AIManager
	{
		AIManager_Instance = 0x36F0,							//13.19
		AiManager_Manager = 0x10,
		TargetPosition = 0x14,
		IsMoving = 0x2BC,
		CurrentSegment = 0x2C0,
		PathStart = 0x2D0,
		PathEnd = 0x2DC,
		Segments = 0x2E8,
		SegmentsCount = 0x2F0,
		DashSpeed = 0x300,
		IsDashing = 0x324,
		Position = 0x414,
	};
 
	// Others
	enum CharacterData {
		//SpellObject : [[<League of Legends.exe> + 0x21C4A28]+30B8 +(0x8 *SPELLINDEX)]
 
		//		*CharData
		//		-SkinName
		//		-Stack
		//		-SkinHash
		//		-Size
		//		-ObjTypeDetailed
		//		-ObjType
		// 
		//			*CharData_Data
		//				-HPBarHeight
		//				
		//				
		//				
 
 
		CharData = 0x3590,										//13.19
		Stack_Push = 0x19B9C0,									//13.19
		Stack_Update = 0x185800,								//13.19
 
		SkinName = 0x8,											//13.19
		Stack = 0x35C0,											//13.19 // 48 8D 8B ? ? ? ? 48 89 44 24 ? C7 44 24
		SkinHash = 0x18,										//13.19
 
		Size = 0xD7,											//13.18
		ObjTypeDetailed = 0x20,									//13.17
		ObjType = 0x7A9,										//13.18
 
		CharData_Data = 0x28,									//13.19
		HPBarHeight = 0xC4,										//13.19
		
		//Idk, need to find more
		GetCharacterPackage = 0xC4,								//13.  //E8 ?? ?? ?? ?? 41 C1 EE 1F 41 B9 01 00 00 00
 
 
	};
 
	enum VFunc {
		VF_OnProcessSpellCast = 30,								//13.18
		VF_BoundingRadius = 36,									//13.18
		
		VF_AiManager = 150,
		VF_GetRespawnTimeRemaining = 222,
		VF_GetBuffManager = 216,
		VF_GetSpellbook = 217,
		VF_GetRespawnTime = 235,
		VF_GetRemainingRespawnTime = 236,
	};
};
[offsetleague.txt](https://github.com/lucifer00123/Handbot/files/12738428/offsetleague.txt)

**Comment by lucifer00123** [comment]
solved

**Comment by lucifer00123** [comment]
updated
